name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/app-interface-and-design/images/battery.png
    - assets/app-interface-and-design/images/calendar.png
    - assets/app-interface-and-design/images/combined-shape.png
    - assets/app-interface-and-design/images/wi-fi.png
    - assets/app-interface-and-design/images/iconly-bold-time-square.png
    - assets/app-interface-and-design/images/iconly-bold-calendar.png
    - assets/app-interface-and-design/images/battery-qKF.png
    - assets/app-interface-and-design/images/iconly-bold-message.png
    - assets/app-interface-and-design/images/battery-Tv9.png
    - assets/app-interface-and-design/images/combined-shape-x8Z.png
    - assets/app-interface-and-design/images/curved-calendar.png
    - assets/app-interface-and-design/images/wi-fi-Sjb.png
    - assets/app-interface-and-design/images/iconly-bold-time-square-ibB.png
    - assets/app-interface-and-design/images/battery-3yj.png
    - assets/app-interface-and-design/images/search.png
    - assets/app-interface-and-design/images/colorpal3-1.png
    - assets/app-interface-and-design/images/auto-group-7jjt.png
    - assets/app-interface-and-design/images/rectangle-24.png
    - assets/app-interface-and-design/images/ellipse-17.png
    - assets/app-interface-and-design/images/iconly-bold-paper-plus.png
    - assets/app-interface-and-design/images/curved-calendar-9uK.png
    - assets/app-interface-and-design/images/curved-calendar-ZhT.png
    - assets/app-interface-and-design/images/notification-icon.png
    - assets/app-interface-and-design/images/wi-fi-ySy.png
    - assets/app-interface-and-design/images/r-2-1.png
    - assets/app-interface-and-design/images/PSG.png
    - assets/app-interface-and-design/images/ellipse-16.png
    - assets/app-interface-and-design/images/curved-calendar-tVP.png
    - assets/app-interface-and-design/images/ellipse-16-9AR.png
    - assets/app-interface-and-design/images/frame-13.png
    - assets/app-interface-and-design/images/ellipse-17-ass.png
    - assets/app-interface-and-design/images/.png
    - assets/app-interface-and-design/images/calendar-zjb.png
    - assets/app-interface-and-design/images/frame-12.png
    - assets/app-interface-and-design/images/combined-shape-1HK.png
    - assets/app-interface-and-design/images/battery-KYu.png
    - assets/app-interface-and-design/images/battery-HWH.png
    - assets/app-interface-and-design/images/ellipse-28.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-left-circle.png
    - assets/app-interface-and-design/images/ellipse-28-AqX.png
    - assets/app-interface-and-design/images/curved-calendar-uof.png
    - assets/app-interface-and-design/images/curved-calendar-Pnh.png
    - assets/app-interface-and-design/images/notification-icon-2c1.png
    - assets/app-interface-and-design/images/frame-13-44q.png
    - assets/app-interface-and-design/images/ellipse-28-bsP.png
    - assets/app-interface-and-design/images/iconly-bold-info-square.png
    - assets/app-interface-and-design/images/calendar-kJD.png
    - assets/app-interface-and-design/images/frame-13-Qn5.png
    - assets/app-interface-and-design/images/frame-12-EP3.png
    - assets/app-interface-and-design/images/auto-group-x6ly.png
    - assets/app-interface-and-design/images/wi-fi-EMX.png
    - assets/app-interface-and-design/images/curved-calendar-XsX.png
    - assets/app-interface-and-design/images/ellipse-28-pEM.png
    - assets/app-interface-and-design/images/ellipse-17-iMf.png
    - assets/app-interface-and-design/images/calendar-tR7.png
    - assets/app-interface-and-design/images/combined-shape-CPB.png
    - assets/app-interface-and-design/images/wi-fi-NiD.png
    - assets/app-interface-and-design/images/wi-fi-zqP.png
    - assets/app-interface-and-design/images/combined-shape-gSu.png
    - assets/app-interface-and-design/images/curved-calendar-kLH.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-up-circle.png
    - assets/app-interface-and-design/images/curved-calendar-PpV.png
    - assets/app-interface-and-design/images/iconly-bold-location.png
    - assets/app-interface-and-design/images/wi-fi-xzu.png
    - assets/app-interface-and-design/images/wi-fi-KKf.png
    - assets/app-interface-and-design/images/ellipse-16-5Zj.png
    - assets/app-interface-and-design/images/curved-calendar-qYu.png
    - assets/app-interface-and-design/images/auto-group-q9xf.png
    - assets/app-interface-and-design/images/curved-calendar-Ar5.png
    - assets/app-interface-and-design/images/iconly-bold-camera.png
    - assets/app-interface-and-design/images/iconly-bold-image.png
    - assets/app-interface-and-design/images/frame-13-Sh7.png
    - assets/app-interface-and-design/images/iconly-bold-filter.png
    - assets/app-interface-and-design/images/curved-calendar-aHX.png
    - assets/app-interface-and-design/images/combined-shape-YEM.png
    - assets/app-interface-and-design/images/notification-icon-u4u.png
    - assets/app-interface-and-design/images/rectangle-21.png
    - assets/app-interface-and-design/images/iconly-bold-download.png
    - assets/app-interface-and-design/images/ellipse-28-6Wd.png
    - assets/app-interface-and-design/images/iconly-bold-paper-negative.png
    - assets/app-interface-and-design/images/curved-calendar-EnV.png
    - assets/app-interface-and-design/images/battery-PfP.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-down-3.png
    - assets/app-interface-and-design/images/auto-group-j2ky.png
    - assets/app-interface-and-design/images/curved-calendar-wjP.png
    - assets/app-interface-and-design/images/iconly-bold-star.png
    - assets/app-interface-and-design/images/iconly-bold-edit.png
    - assets/app-interface-and-design/images/curved-home-2.png
    - assets/app-interface-and-design/images/notification-icon-YWD.png
    - assets/app-interface-and-design/images/iconly-bold-graph.png
    - assets/app-interface-and-design/images/ellipse-17-GSD.png
    - assets/app-interface-and-design/images/iconly-bold-wallet.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-right-square.png
    - assets/app-interface-and-design/images/combined-shape-rND.png
    - assets/app-interface-and-design/images/iconly-bold-add-user.png
    - assets/app-interface-and-design/images/r-2-1-BMB.png
    - assets/app-interface-and-design/images/iconly-bold-home.png
    - assets/app-interface-and-design/images/frame-12-s6q.png
    - assets/app-interface-and-design/images/battery-1yj.png
    - assets/app-interface-and-design/images/frame-12-yff.png
    - assets/app-interface-and-design/images/iconly-bold-profile.png
    - assets/app-interface-and-design/images/iconly-bold-more-circle.png
    - assets/app-interface-and-design/images/combined-shape-jYM.png
    - assets/app-interface-and-design/images/iconly-bold-lock.png
    - assets/app-interface-and-design/images/curved-calendar-Bv9.png
    - assets/app-interface-and-design/images/iconly-bold-folder.png
    - assets/app-interface-and-design/images/ellipse-16-sY5.png
    - assets/app-interface-and-design/images/curved-calendar-AGH.png
    - assets/app-interface-and-design/images/curved-calendar-uay.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-up.png
    - assets/app-interface-and-design/images/iconly-bold-delete.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-right-2.png
    - assets/app-interface-and-design/images/iconly-bold-video.png
    - assets/app-interface-and-design/images/iconly-bold-paper-plus-rj3.png
    - assets/app-interface-and-design/images/r-2-1-Kus.png
    - assets/app-interface-and-design/images/rectangle-21-ZA1.png
    - assets/app-interface-and-design/images/rectangle-21-Hy3.png
    - assets/app-interface-and-design/images/r-2-1-CKK.png
    - assets/app-interface-and-design/images/rectangle-21-TpV.png
    - assets/app-interface-and-design/images/iconly-bold-filter-2.png
    - assets/app-interface-and-design/images/iconly-bold-close-square.png
    - assets/app-interface-and-design/images/iconly-bold-info-square-hxu.png
    - assets/app-interface-and-design/images/iconly-bold-plus.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-down-2.png
    - assets/app-interface-and-design/images/iconly-bold-calling.png
    - assets/app-interface-and-design/images/iconly-bold-chat.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-down-square.png
    - assets/app-interface-and-design/images/iconly-bold-danger.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-up-square.png
    - assets/app-interface-and-design/images/iconly-bold-document.png
    - assets/app-interface-and-design/images/iconly-bold-call-silent.png
    - assets/app-interface-and-design/images/iconly-bold-logout.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-left-2.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-left-3.png
    - assets/app-interface-and-design/images/iconly-bold-ticket-star.png
    - assets/app-interface-and-design/images/iconly-bold-shield-fail.png
    - assets/app-interface-and-design/images/iconly-bold-setting.png
    - assets/app-interface-and-design/images/iconly-bold-unlock.png
    - assets/app-interface-and-design/images/iconly-bold-discount.png
    - assets/app-interface-and-design/images/iconly-bold-hide.png
    - assets/app-interface-and-design/images/iconly-bold-edit-square.png
    - assets/app-interface-and-design/images/iconly-bold-volume-off.png
    - assets/app-interface-and-design/images/iconly-bold-swap.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-right-circle.png
    - assets/app-interface-and-design/images/iconly-bold-call.png
    - assets/app-interface-and-design/images/iconly-bold-work.png
    - assets/app-interface-and-design/images/iconly-bold-image-2.png
    - assets/app-interface-and-design/images/iconly-bold-paper.png
    - assets/app-interface-and-design/images/iconly-bold-game.png
    - assets/app-interface-and-design/images/iconly-bold-play.png
    - assets/app-interface-and-design/images/iconly-bold-paper-upload.png
    - assets/app-interface-and-design/images/iconly-bold-more-square.png
    - assets/app-interface-and-design/images/iconly-bold-tick-square.png
    - assets/app-interface-and-design/images/iconly-bold-calendar-T8M.png
    - assets/app-interface-and-design/images/iconly-bold-2-user.png
    - assets/app-interface-and-design/images/iconly-bold-volume-down.png
    - assets/app-interface-and-design/images/iconly-bold-discovery.png
    - assets/app-interface-and-design/images/iconly-bold-call-missed.png
    - assets/app-interface-and-design/images/iconly-bold-3-user.png
    - assets/app-interface-and-design/images/iconly-bold-show.png
    - assets/app-interface-and-design/images/iconly-bold-volume-up.png
    - assets/app-interface-and-design/images/iconly-bold-time-square-y5T.png
    - assets/app-interface-and-design/images/iconly-bold-voice.png
    - assets/app-interface-and-design/images/iconly-bold-time-circle.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-right-3.png
    - assets/app-interface-and-design/images/iconly-bold-bag.png
    - assets/app-interface-and-design/images/iconly-bold-profile-Q81.png
    - assets/app-interface-and-design/images/iconly-bold-activity.png
    - assets/app-interface-and-design/images/iconly-bold-search.png
    - assets/app-interface-and-design/images/iconly-bold-notification.png
    - assets/app-interface-and-design/images/iconly-bold-login.png
    - assets/app-interface-and-design/images/iconly-bold-heart.png
    - assets/app-interface-and-design/images/iconly-bold-voice-2.png
    - assets/app-interface-and-design/images/iconly-bold-bag-2.png
    - assets/app-interface-and-design/images/iconly-bold-shield-done.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-down.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-up-3.png
    - assets/app-interface-and-design/images/iconly-bold-category.png
    - assets/app-interface-and-design/images/iconly-bold-paper-fail.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-left-square.png
    - assets/app-interface-and-design/images/iconly-bold-bookmark.png
    - assets/banner-for-figma-community/images/shadow-bg.png
    - assets/banner-for-figma-community/images/shadow-bg-bKo.png
    - assets/app-interface-and-design/images/iconly-bold-info-circle.png
    - assets/app-interface-and-design/images/iconly-bold-scan.png
    - assets/app-interface-and-design/images/iconly-bold-ticket.png
    - assets/app-interface-and-design/images/iconly-bold-message-6sB.png
    - assets/banner-for-figma-community/images/main.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-right.png
    - assets/app-interface-and-design/images/iconly-bold-password.png
    - assets/banner-for-figma-community/images/iphone-12-mockup-front-view-label.png
    - assets/app-interface-and-design/images/iconly-bold-buy.png
    - assets/app-interface-and-design/images/iconly-bold-chart.png
    - assets/banner-for-figma-community/images/vector.png
    - assets/app-interface-and-design/images/iconly-bold-paper-download.png
    - assets/app-interface-and-design/images/combined-shape-dpm.png
    - assets/app-interface-and-design/images/iconly-bold-upload.png
    - assets/banner-for-figma-community/images/shadow-bg-AAu.png
    - assets/app-interface-and-design/images/wi-fi-uk5.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-up-2.png
    - assets/assets/images/iconly-bold-message-rzM.png
    - assets/banner-for-figma-community/images/vector-63T.png
    - assets/app-interface-and-design/images/iconly-bold-send.png
    - assets/banner-for-figma-community/images/main-ZmK.png
    - assets/app-interface-and-design/images/battery-kvm.png
    - assets/app-interface-and-design/images/iconly-bold-arrow-down-circle.png
    - assets/banner-for-figma-community/images/vector-5kD.png
    - assets/banner-for-figma-community/images/iphone-12-pro-61-mockup-label.png
    - assets/banner-for-figma-community/images/vector-irm.png
    - assets/banner-for-figma-community/images/main-Xe9.png
    - assets/assets/images/-3VK.png
    - assets/banner-for-figma-community/images/iphone-12-pro-61-mockup-right-view-label.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
